app:
  restart: always
  build: ./app
  command: php -S 0.0.0.0:8000 -t /app/web
  ports:
    - "8000:8000"

nginx:
  restart: always
  build: ./nginx
  ports:
    - "80:80"
    - "443:443"
  links:
    - app:app
